version: "3"

services:
  api:
    image: node:16
    volumes:
      - ./:/app
    ports:
      - 9229:9229
      - 3000:3000
    working_dir: /app
    command: npx nodemon -- --inspect=0.0.0.0 dist/index.js
    depends_on:
      - build
    networks: 
      - boldarev-services
  build:
    image: node:16
    volumes:
      - ./:/app
    working_dir: /app
    command: npx tsc -w --preserveWatchOutput
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks: 
      - boldarev-services 

networks:
  boldarev-services:
    external:
      name: boldarev-services 

volumes:
  data:
